"""<TITLE>

<DESCRIPTION>

Author(s): Alphonse Birane Thiaw
Scot-Lab Universite de Sherbrooke
"""


import os
from scripts.manifest_utils import ManifestHolderPE, ManifestHolderSR

# ===============
# Config
# ===============

configfile: "config/resources.yaml"

GTF        = config["gtf"]
GTF_PREFIX = os.path.splitext(GTF)[0]
FASTA      = config["fasta"]
FASTQ_DIR  = config["fastq_dir"]
OUTPUT_DIR = config["output_dir"]
MANIFEST   = config["manifest"]


# ===============
# Manifest
# ===============
manifest = ManifestHolderPE(MANIFEST)
SAMPLES  = manifest.get_samples()


# ===============
# Règles
# ===============
rule run_all:
    input:
        f"{OUTPUT_DIR}/report/multiqc/qc_multiqc_report.html",
        f"{OUTPUT_DIR}/report/star/star_multiqc_report.html",
        f"{OUTPUT_DIR}/coco_merge/samples_merged_coco_tpm.tsv"

rule downloads_coco:
    output:
        check = "../tools/coco_downloads.done",
		coco_folder = directory("../tools/coco")
    params:
        coco_link = config["path"]["coco_link"]
    conda:
        "envs/git.yaml"
    shell:
        """
        git clone {params.coco_link} {output.coco_folder}
		touch {output.check}
        """

rule fastp:
    input:
        R1 = lambda wc: manifest.get_fastq_path(True, wc.sample),
        R2 = lambda wc: manifest.get_fastq_path(False, wc.sample)
    output:
        fp1         = "../tempdir/fastp/{sample}/{sample}_R1_fastp.fq.gz",
        fp2         = "../tempdir/fastp/{sample}/{sample}_R2_fastp.fq.gz",
        html_report = "../tempdir/fastp/report/{sample}_fastp.html",
        json_report = "../tempdir/fastp/report/{sample}_fastp.json"
    threads:
        32
    params:
        options = [
            "--qualified_quality_phred 30",
            "--cut_window_size 1",
            "--cut_mean_quality 30",
            "--cut_front",
            "--cut_tail"
        ]
    log:
        "../tempdir/logs/fastp/{sample}_fastp.log"
    conda:
        "envs/fastp.yaml"
    shell:
        """
        fastp \
            -i {input.R1} -I {input.R2} \
            -o {output.fp1} -O {output.fp2} \
            -h {output.html_report} \
            -j {output.json_report} \
            --thread {threads} \
            {params.options} \
            &> {log}
        """

rule fastq_report:
    input:
        expand("../tempdir/fastp/report/{sample}_fastp.html", sample=SAMPLES)
    output:
        report = f"{OUTPUT_DIR}/report/multiqc/qc_multiqc_report.html"
    params:
        fastp_dir  = "../tempdir/fastp/report",
        report_dir = f"{OUTPUT_DIR}/report/multiqc"
    conda:
        "envs/multiqc.yaml"
    shell:
        """
        multiqc {params.fastp_dir} \
            --outdir {params.report_dir} \
            --filename qc_multiqc_report.html
        """

rule star_index:
    input:
        fasta = FASTA,
        gtf   = GTF
    output:
        chrNameLength = "../tempdir/star/star_index/chrNameLength.txt"
    threads:
        32
    params:
        index_dir = "../tempdir/star/star_index/"
    log:
        "../tempdir/logs/star/star_index/star_index.log"
    conda:
        "envs/star.yaml"
    shell:
        """
        STAR --runMode genomeGenerate \
            --runThreadN {threads} \
            --genomeDir {params.index_dir} \
            --genomeFastaFiles {input.fasta} \
            --sjdbGTFfile {input.gtf} \
            --sjdbOverhang 74 \
            &> {log}
        """

rule star:
    input:
        R1    = rules.fastp.output.fp1,
        R2    = rules.fastp.output.fp2,
        index = rules.star_index.output
    output:
        bam = "../tempdir/star/star_align/{sample}/Aligned.sortedByCoord.out.bam"
    threads:
        32
    params:
        outdir    = "../tempdir/star/star_align/{sample}/",
        index_dir = "../tempdir/star/star_index"
    log:
        "../tempdir/logs/star/star_align/{sample}.log"
    conda:
        "envs/star.yaml"
    shell:
        """
        STAR --runMode alignReads \
            --genomeDir {params.index_dir} \
            --readFilesIn {input.R1} {input.R2} \
            --runThreadN {threads} \
            --readFilesCommand zcat \
            --outFilterType BySJout \
            --outStd Log \
            --outSAMunmapped None \
            --outSAMtype BAM SortedByCoordinate \
            --outFileNamePrefix {params.outdir} \
            --outFilterScoreMinOverLread 0.3 \
            --outFilterMatchNminOverLread 0.3 \
            --outFilterMultimapNmax 100 \
            --winAnchorMultimapNmax 100 \
            --alignEndsProtrude 5 ConcordantPair \
            &> {log}
        """

rule find_star_log:
    input:
        expand("../tempdir/star/star_align/{sample}/Aligned.sortedByCoord.out.bam", sample=SAMPLES)
    params:
        path = "../tempdir/star/star_align/"
    output:
        file = "../tempdir/star/star_report/path_log_star_align.txt"
    shell:
        """
        find {params.path} -type f > {output.file}
        """

rule star_multiqc:
    input:
        star_in = rules.find_star_log.output.file
    output:
        report = f"{OUTPUT_DIR}/report/star/star_multiqc_report.html"
    params:
        report_dir = f"{OUTPUT_DIR}/report/star"
    conda:
        "envs/multiqc.yaml"
    shell:
        """
        multiqc --file-list {input.star_in} \
            --outdir {params.report_dir} \
            --filename star_multiqc_report.html
        """

rule coco_ca:
    input:
    	check = rules.downloads_coco.output.check,
        gtf = GTF
    output:
        gtf_corrected = f"{GTF_PREFIX}.correct_annotation.gtf"
    log:
        "../tempdir/logs/coco_ca/coco_annotation.log"
    params:
        coco_folder = rules.downloads_coco.output.coco_folder
    conda:
        "envs/coco.yaml"
    shell:
        """
        export PATH={params.coco_folder}/bin:$PATH
        coco ca {input.gtf} &> {log}
        """

rule coco_cc:
    input:
        gtf = rules.coco_ca.output.gtf_corrected,
        bam = rules.star.output.bam
    output:
        tab = f"{OUTPUT_DIR}/coco/{{sample}}.tsv"
    log:
        "../tempdir/logs/coco/{sample}.log"
    threads:
        32
    params:
        coco_folder = rules.downloads_coco.output.coco_folder
    conda:
        "envs/coco.yaml"
    shell:
        """
        export PATH={params.coco_folder}/bin:$PATH
        coco cc \
            --strand 1 \
            --thread {threads} \
            --paired \
            {input.gtf} {input.bam} \
            {output.tab} \
            &> {log}
        """

rule cocoCount_merge:
    input:
        cc = expand(f"{OUTPUT_DIR}/coco/{{sample}}.tsv", sample=SAMPLES)
    output:
        tab_tpm   = f"{OUTPUT_DIR}/coco_merge/samples_merged_coco_tpm.tsv",
        tab_count = f"{OUTPUT_DIR}/coco_merge/samples_merged_coco_count.tsv"
    params:
        pathdir = f"{OUTPUT_DIR}/coco"
    conda:
        "envs/python.yaml"
    shell:
        """
        python3 ./scripts/cocoCount_merged.py \
            -f tpm \
            -i {params.pathdir} \
            -o {output.tab_tpm}
        python3 ./scripts/cocoCount_merged.py \
            -f count \
            -i {params.pathdir} \
            -o {output.tab_count}
        """
